### ISSUE TITLE
customize welcome email

### ISSUE THREAD

**Issue by utnapischtim** [tu-graz-library/invenio-config-tugraz#55]
The Email which is send out after the first login should be more user friendly.

It would be nice to have a personalized salutation e.g. Dear Ms Jane Doe

Also links to the help page or the handbook would be nice, further a link to the "Nutzungsbedingungen" would be nice

**Comment by mb-wali** [comment]
## reference
Register func:

https://github.com/inveniosoftware/invenio-accounts/blob/0ae2d782f1346b0b8e03810e702cc89875bd762e/invenio_accounts/utils.py#L150

--

Celery task:
https://github.com/inveniosoftware/invenio-accounts/blob/0ae2d782f1346b0b8e03810e702cc89875bd762e/invenio_accounts/tasks.py#L24

--

Flask-mail:
https://pythonhosted.org/Flask-Mail/
