### ISSUE TITLE
add a new HOSTNAME var

### ISSUE THREAD

**Issue by mb-wali** [tu-graz-library/invenio-config-tugraz#90]
since `SITE_HOSTNAME` is deprecated from invenioRDM - 
our [mail template](https://github.com/tu-graz-library/invenio-config-tugraz/blob/c43c36ece3809216c5122cb6cf2bf6a346f3b201/invenio_config_tugraz/templates/security/email/welcome.txt#L9) has a empty domain name:
```bash
Dear user,

Welcome to the Repository of TU Graz!

To help you get started, here are some useful links:

    - Guidelines: Repository Guide (how to upload files) (https:///guide)
    - Search Guide (https:///help/search)
    - Terms And Conditions (https:///terms)
    - Data Protection Rights (https:///gdpr)

If you require any assistance please do not hesitate to contact us at repository-support@tugraz.at.

Best regards,
TU Graz Repository Team
```
## proposed solution
Add a new config variable inside `config.py` call it `CONFIG_TUGRAZ_HOSTNAME` and should be overridable via `INVENIO_CONFIG_TUGRAZ_HOSTNAME`.

**Comment by rekt-hard** [comment]
What about the config variable `SITE_UI_URL` ? This is also used in `communities` and `records-resources` for creating links.

**Comment by mb-wali** [comment]
> What about the config variable `SITE_UI_URL` ? This is also used in `communities` and `records-resources` for creating links.

good catch - please change to `SITE_UI_URL`
